---
language: node_js
node_js:
  - "6"
  - "8"
  - "10"

sudo: false

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: lint
      node: 10
      script: eslint .

stages:
  - lint # fast fail if linting does not pass
  - test

script:
  - npm test && ./smoke_test/run.sh
