---
language: node_js
node_js:
  - "6"
  - "8"
  - "10"

sudo: false

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: lint
      node: 10
      script: eslint .
    - stage: test-node-6
      node: 6
      script: npm test && ./smoke-test/run.sh
    - stage: test-node-8
      node: 8
      script: npm test && ./smoke-test/run.sh
    - stage: test-node-10
      node: 10
      script: npm test && ./smoke-test/run.sh


